---

sudo: false
dist: bionic
language: generic
python:
    - "2.7"
    - "3.7"
install:
    - pip install --user --upgrade pip
    - pip install --user tox
    - tox --version
script: tox -e travis
notifications:
    email:
        on_success: change
        on_failure: always

...
